config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/:generate_url', to: 'welcome#redirect', as: 'redirect'

  resources :pages, path: '/admin/pages'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :url, presence: true
end

app/models/page.rb
class Page < ApplicationRecord

  validates :name, :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :find_page, only: [:edit, :update, :show, :destroy]


  def new
    @page = Page.new
    end


  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to (root_path)
    else render :edit
    end
  end

  def edit
  end

  def show
  end

  def destroy
    if @page.destroy
      redirect_to pages_path
    else
      redirect_to pages_path, error: 'Don\'t happened delete'
    end
  end

  def index
    @pages = Page.all
  end

  def page_params
    params[:page].permit(:name, :description)
  end

  def find_page
    @page = Page.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require 'socket'

  def index
    if get_url_params
      if (@link = Link.where(url: slice_url(get_url_params)).take)
      else
         @link = Link.create(
            url: slice_url(get_url_params),
            generate_url: generate_url
        )
      end
    end
  end

  def redirect
    if (link = Link.where(generate_url: params[:generate_url]).take)
      redirect_to 'http://' + link[:url]
    else
      redirect_to root_path, flash: {errors: 'Please generate url'}
    end
  end

  def generate_url
    # render text: url.unpack('U*')
      if (generate_url = Link.last(1).empty? ? false :  Link.last[:generate_url])
        generate_url = generate_url.succ
      else
        generate_url = 'A0'
      end

    generate_url
  end

  def slice_url(url)

    if url.include? 'http://'
      url = url.gsub(/http:\/\//, '')
    elsif url.include? 'https://'
      url = url.gsub(/https:\/\//, '')
    end

    url
  end

  def get_url_params
    params[:url];
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Short" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= link_to "Main", root_path, class: 'navbar-brand'   %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Pages", pages_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--<div class="col-lg-3">-->
          <!--<div class="well sidebar-nav">-->
            <!--<h3>Sidebar</h3>-->
            <!--<ul class="nav nav-list">-->
              <!--<li class="nav-header">Sidebar</li>-->
              <!--<li><%= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
        <!--</div>&lt;!&ndash;/span&ndash;&gt;-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for (@page) do |f| %>

    <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :description %>

    <%= f.button :submit %>

<% end %>

app/views/pages/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

app/views/pages/index.html.erb
<h1>All Pages</h1>

<table class="table">
  <thead>
  <tr>
    <th>
      Название
    </th>
  </tr>
  </thead>

  <tbody>
  <% @pages.each do |page|%>
  <tr>
    <td>
      <%= page.name %>
    </td>
    <td>
      <%= link_to 'edit', edit_page_path(page)%>
    </td>
    <td>
      <%= link_to 'destroy', page_path(page), method: :delete, data: {confirm: 'Are you sure?'}%>
    </td>
  </tr>
      <% end %>
  </tbody>
</table>

<%= link_to 'create page', new_page_path%>

app/views/pages/new.html.erb
<h1>new</h1>

<%= render 'form' %>

app/views/welcome/index.html.erb
<% if flash[:errors] %>
    <h2 style="color: red"><%=	flash[:errors]%> </h2>
<%	 end %>

<form action="<% root_path %>" method="get">

  <div class="form-group">
    <label for="url" class="control-label string required">Enter url name</label>
    <input type="text" name="url" class="form-control string required">
  </div>
  <button class="btn btn-default">Generate</button>

</form>
<br/>

<% if @link %>
    <address>
      <h2><strong>Your Link</strong></h2><br>
      <h2><a href="<%= redirect_path(@link[:generate_url]) %>" methods="post"><%= (request.port ? request.host_with_port : request.host) + redirect_path(@link[:generate_url]) %></a></h2>
    </address>
<% end %>





  `